### ISSUE TITLE
Attempting to Run in Python 3

### ISSUE THREAD

**Issue by windowshopr** [WWojnar/graphology#2]
I'm working on trying to get the code to work in python 3, and receive the following error:

Traceback (most recent call last):
  File "mainWindow.py", line 44, in openSlantChecker
    pixmap = self.mainPicture.pixMapToShare
AttributeError: 'RubberbandEnhancedLabel' object has no attribute 'pixMapToShare'

Any ideas? Is there a dependency I don't have installed yet? Thanks!

**Comment by windowshopr** [comment]
Soooo no plans on updating to Python 3 before closing the issue? 😂

**Comment by WWojnar** [comment]
Not sure what I can do with this (and if it is complete solution) but will look through bringing this back up and porting.

**Comment by WWojnar** [comment]
This seems to be written in Python 3

You need to have PyQt5. From history records it seems that this runs on 5.6.

Its possible that it did not initialize class RubberbandEnhancedLabel(QtWidgets.QLabel):


What is your setup for this?

**Comment by windowshopr** [comment]
Uhh, no it's not written for Python 3, very evident from the print statements alone:

```
PS Z:\Python_Projects\Graphology\graphology> python dist.py
  File "Z:\Python_Projects\Graphology\graphology\dist.py", line 31
    print DistAnalyzer.analyze(ratio)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
PS Z:\Python_Projects\Graphology\graphology> python mainWindow.py
  File "Z:\Python_Projects\Graphology\graphology\mainWindow.py", line 205
    print event.pos()
    ^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
PS Z:\Python_Projects\Graphology\graphology>
```

My setup is Windows 10, Python 3.10 now. Also running into an issue trying to install PyQt5 with `pip install PyQt5` as it currently results in:

```
PS C:\Windows\system32> pip install PyQt5 -U
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
ERROR: Could not find a version that satisfies the requirement PyQt5 (from versions: none)
ERROR: No matching distribution found for PyQt5
```

...which is an odd error as I don't even have Python 2 installed on this machine, but that's a secondary issue. We can close this issue as it seems there's a fair amount of work that would need to go into converting it. Thanks!
